### ISSUE TITLE
Add node-lts to bases

### ISSUE THREAD

**Issue by thematrimix** [tsconfig/bases#136]
It seems it would be quite helpful to have a base that maps to node lts (at current 16.13.0 to 16.X). An example were it could be used in in Github Actions where one can always target node lts as follows.

```yml
name: Setup
description: Setup pnpm, Node and install dependencies
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "lts/*"

    - name: Install NPM packages
      run: pnpm install
      shell: bash
```

The key here is node-version: "lts/*" which as one would guess will always be the latest lts. Therefore  in our code it would be nice to create a base tsconfig that extends from a tsconfig base current lts. At the time of this issue the current lts is 16.18.0 so one could either copy the current node-16 bases and start new set or maybe script a way to publish whatever the current lts mapping is and publish as node-lts then there would be only one set to manage.
